exclude: ^(venv/|.venv/|tests/)
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-tqdm>=4.66.0.20240417
          - randomname>=0.2.1
          - "https://download.pytorch.org/whl/cpu/torch-2.3.1%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=2141a6cb7021adf2f92a0fd372cfeac524ba460bd39ce3a641d30a561e41f69a"
        args:
          - "--fast-module-lookup"
          - "--disallow-any-generics"
          - "--disable-error-code=import-untyped"
