exclude: ^(venv/|.venv/|tests/)
repos:
  - repo: local  # Remove this when a new version of pre-commit-hooks (>4.6.0) is released
    hooks:
      - id: check-illegal-windows-names
        name: check illegal windows names
        entry: Illegal Windows filenames detected
        language: fail
        files: '(?i)((^|/)(CON|PRN|AUX|NUL|COM[\d¹²³]|LPT[\d¹²³])(\.|/|$)|[<>:\"\\|?*\x00-\x1F]|/[^/]*[\.\s]/|[^/]*[\.\s]$)'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      # - id: check-illegal-windows-names  # Uncomment this when a new version of pre-commit-hooks (>4.6.0) is released
      - id: check-json
      - id: pretty-format-json
        args: [ "--autofix", "--no-sort-keys" ]
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: name-tests-test
        args: [ "--pytest-test-first" ]
      - id: trailing-whitespace
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.18
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.20
    hooks:
      - id: pymarkdown
        args:
          - "-d"
          - "MD013, MD041"  # Line length, First line in file should be a top level heading
          - "scan"
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
      - id: sphinx-lint
        args: [ "--enable=default-role" ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff-format
      - id: ruff
  # Pydoclint is useful, but gives too many false positives
  #  - repo: https://github.com/jsh9/pydoclint
  #    rev: 0.4.1
  #    hooks:
  #      - id: pydoclint
  #        args: [ "--quiet" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "--find-links=https://download.pytorch.org/whl/torch_stable.html"
          - types-tqdm>=4.66.0.20240417
          - randomname>=0.2.1
          - "torch==2.3.1+cpu"
        args:
          - "--fast-module-lookup"
          - "--disallow-any-generics"
          - "--disable-error-code=import-untyped"
