cli:
  plugins:
    pycoverage:
      report_type: "xml"
coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 100%
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 0%
        threshold: 100%
      - type: patch
        target: 0%
        threshold: 100%
  individual_flags:
    - name: smart-tests
      carryforward_mode: "labels"
