cli:
  plugins:
    pycoverage:
      report_type: "json"
codecov:
  require_ci_to_pass: true
coverage:
  status:
    project:
      default:
        target: 0%
flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"
