cli:
  plugins:
    pycoverage:
      report_type: "xml"
coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 100%
flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"
