name: Unit Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3.0.2
      - name: Setup the environment
        run: rye sync --all-features
      - name: Run ATS
        uses: codecov/codecov-ats@v0.3.0
        env:
          CODECOV_STATIC_TOKEN: ${{ secrets.CODECOV_STATIC_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run tests
        run: cat codecov_ats/tests_to_run.txt | rye run pytest --cov=./ --cov-branch --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4.4.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: smart-tests
          plugins: pycoverage,compress-pycoverage
          fail_ci_if_error: true
